### ISSUE TITLE
Add 'Edit this page on GitHub' link at the beginning of every doc page

### ISSUE THREAD

**Issue by fmontesi** [jolie/docs#103]
See title. The link should just open the relevant page on github in the browser, in edit mode. I think it'd really help people with editing mistakes promptly, compared to having to go to the codebase and manually find the page to edit.

**Comment by kicito** [comment]
Agree, I will look to see if there is an option to configure this for mdBook.

**Comment by kicito** [comment]
Thanks to mdbook the feature is available to use. Now every page should have the button present at the top right.

**Comment by fmontesi** [comment]
Super, thanks! :)
