### ISSUE TITLE
Chapter 2.3.1.2 xml example

### ISSUE THREAD

**Issue by adelmogentilini** [jolie/docs#106]
Chapter 2.3.1.2
The code says that:

javascript
Copia codice
main  {
    readFile@file( {
        filename = "note.xml"
        format = "xml"
    } )( data )
    // data is now { node << { from = "John" to = "Jane" content = "I made pasta" } }
}
But the data contained in data will be { note << { from = "John" to = "Jane" content = "I made pasta" } }, not node. It’s a simple mistake, but the similarity to a keyword like node could make it unclear.

**Comment by klag** [comment]
fixed,

thanks
