### ISSUE TITLE
Media

### ISSUE THREAD

**Issue by adelmogentilini** [jolie/docs#107]
Dcoumentation:

_Jolie currently supports four media:

local (Jolie in-memory communication);
socket (TCP/IP sockets).
btl2cap (Bluetooth L2CAP);
rmi (Java RMI);
localsocket (Unix local sock_ets);

they are FIVE.

**Comment by klag** [comment]
Could you provide the link of the documenation page?

**Comment by adelmogentilini** [comment]
https://docs.jolie-lang.org/v1.13.x-git/language-tools-and-standard-library/basics/ports/index.html

**Comment by klag** [comment]
fixed

thanks
