### ISSUE TITLE
StringUtils

### ISSUE THREAD

**Issue by adelmogentilini** [jolie/docs#108]
I believe the entire page is wrong. The purpose of each individual function is "Operation documentation: Returns true if the string contains .substring," and the required parameters don’t seem correct. They all appear to be those of the search function, and if you want to use a different one, there’s no way to know what parameters to use.

**Comment by mwallnoefer** [comment]
Should have been fixed: https://docs.jolie-lang.org/v1.13.x-git/language-tools-and-standard-library/standard-library-api/string-utils.html
