### ISSUE TITLE
Data structure

### ISSUE THREAD

**Issue by adelmogentilini** [jolie/docs#110]
This structure:

d.greeting = "hello";
d.first = "to the";
d.first.second = "world";
d.first.third = "!";
is said to correspond to this:

d
|_ greeting = "hello"
|_ first = "to the"
.....|_ first.second = "world"
......|_ first.third = "!"

but I believe it actually corresponds to this:

d
|_ greeting = "hello"
|_ first = "to the"
.....|_ second = "world"
......|_ third = "!"

The json rappresentation is {"greeting":"hello","first":{"$":"to the","third":"!","second":"world"}} so i think is  incorrect first.second and first.third.

**Comment by adelmogentilini** [comment]
sorry tab is not good represented 
`d
|_ greeting = "hello"
|_ first = "to the"
    |_ first.second = "world"
    |_ first.third = "!"`

the second is 
`d
|_ greeting = "hello"
|_ first = "to the"
    |_ second = "world"
    |_ third = "!"`

**Comment by klag** [comment]
Could you provide the link of the documentation page related to this issue?

**Comment by adelmogentilini** [comment]
i refer to this page 
https://docs.jolie-lang.org/v1.13.x-git/language-tools-and-standard-library/basics/data-structures/index.html
the section `[<< - copying an entire tree structure](https://docs.jolie-lang.org/v1.13.x-git/language-tools-and-standard-library/basics/data-structures/index.html#--copying-an-entire-tree-structure)`

**Comment by klag** [comment]
Fixed

Many Thanks

**Comment by klag** [comment]
Hi @kicito , I fixed the page and I can see my changes in edit, but the documentation on the web is still the old one.
Do we have to force the generation of the docs?

**Comment by kicito** [comment]
I've fixed the GitHub actions, which should now build and push the image after the version branch is pushed to the remote. The web content should be updated to align with the most recent commit.

**Comment by klag** [comment]
Thanks
