### ISSUE TITLE
Inclusion file

### ISSUE THREAD

**Issue by adelmogentilini** [jolie/docs#112]
The notation for the file import should be provided, as it is for StringUtils, for example. In other cases, since it's not specified, you proceed by trial and error.

**Comment by klag** [comment]
You mean, before any doc of the standard library?

**Comment by adelmogentilini** [comment]
Yes an annotation like in StringUtils 
`[StringUtils](https://docs.jolie-lang.org/v1.13.x-git/language-tools-and-standard-library/standard-library-api/string_utils.html#stringutils)
Inclusion file:

include "string_utils.iol" from string_utils import StringUtils`

**Comment by mwallnoefer** [comment]
Duplicate of issue #43 which has been fixed.
