### ISSUE TITLE
Issues in section "Termination and Compensation"

### ISSUE THREAD

**Issue by TommasoAzz** [jolie/docs#36]
Hello,
I found some issues in the section "Termination and Compensation" for Jolie 1.10.x.
I'm going to list them here:
- the image in "Termination and Compensation: concepts" is not shown in the documentaion website (but it does get shown in the markdown file) since the path is incorrect;
- in the examples in sections **Compensation, the primitive `comp`** and **Installation-time variable evaluation**, under Basics > Fault Handling > Termination and Compensation either the `install` directive is matching a wrong fault or the wrong fault is thrown.
See [here](
https://github.com/jolie/docs/blob/v1.10.x/web/language-tools-and-standard-library/basics/fault-handling/termination_and_compensation.md) (rows 179-201, 341-364).

**Comment by klag** [comment]
Hi Tommaso, thank you for your feedback. 
I fixed the page, it should be online in a while.

**Comment by TommasoAzz** [comment]
Great, thank you!
