### ISSUE TITLE
Installing Jolie from sources (tab "compile from sources")

### ISSUE THREAD

**Issue by SuperMauro1966** [jolie/docs#45]
https://www.jolie-lang.org/downloads.html

When installing jolie from source (Ubuntu/Linux subsystem in Windows) 

I have noticed that there is an imprecision in the guide.

After running

scripts / dev-setup.sh ~ / bin

running jolie --version produces the notoriuous error

"Error: Could not find or load main class jolie.Jolie"

This type of error is mentioned in the installation procedure with the installer, and not in the topic "installing from from the sources".

Inside the system the isn't the path (/usr/lib/jolie) suggested by the guide to corret the problem (see below)

echo 'export JOLIE_HOME = "/usr/lib/jolie"' >> ~ / .bash_profile

To solve the problem the user has to set in .bashrc (.bash_profile or in /etc/.profile or /etc/bash_bashrc)
the follow line
export JOLIE_HOME=<path to cloned project>/dist/jolie

where <path to cloned project> is the path in the filesystem where you have cloned the project.

**Comment by mwallnoefer** [comment]
I have checked the website: https://github.com/jolie/website/blob/master/www/downloads.md.

So I guess _/usr/lib/jolie_ is taken as path when you are using the JAR-based installer (first section) and _~/bin/jolie-dist_  (or something similar) when you are using the _dev-setup.sh_ script. Not sure how to emphasise the difference here.
