### ISSUE TITLE
StringUtils calls - errorneous title descriptions

### ISSUE THREAD

**Issue by SuperMauro1966** [jolie/docs#50]
At the page https://docs.jolie-lang.org/v1.10.x/language-tools-and-standard-library/standard-library-api/string_utils.html#valueToPrettyString

The operation
valueToPrettyString

has the following description
Operation documentation: checks if the passed string starts with a given prefix

from the description is not immediately understandable that the operation transform a Jolie custom data type to a string
Invocation template:

valueToPrettyString@StringUtils( request )( response )

**Comment by mwallnoefer** [comment]
In this case the description has been fixed, but not for all the other StringUtils calls (_toLowerCase()_, _length()_, _match()_ etc. etc.).

Continuing the discussion in issue #62.
