### ISSUE TITLE
execution syntax

### ISSUE THREAD

**Issue by SuperMauro1966** [jolie/docs#59]
In the documentation, the allowed syntax is indicated as

execution {<mode>}

but in the recent article of Fabrizio, there is another form

execution : <mode>

**Comment by mwallnoefer** [comment]
Both syntaxes are considered valid, maybe add a hint somewhere in the docs?

**Comment by fmontesi** [comment]
The new one with : is recommended. I have removed many unnecessary
characters over the past years, put Jolie more in line with 'modern' prog
lang syntax, and tried to update docs accordingly to follow the recommended
'simple' syntax, but there are probably holes here and there...

Another example is that we don't need to put dots in front of subnode names
inside of type definitions.
