### ISSUE TITLE
Wrong links in Protocol page (HTTPS, SODEPS)

### ISSUE THREAD

**Issue by SuperMauro1966** [jolie/docs#76]
In the page

https://docs.jolie-lang.org/v1.10.x/language-tools-and-standard-library/protocols/ssl/

the links embedded inside the following line (SODEPS , HTTPS)

SSL (Secure Sockets Layer) is not a communication protocol on its own and it is used as a wrapping for SSL-based secure protocols, like SODEPS and HTTPS.

are not working (wrong redirection)

**Comment by klag** [comment]
Fixed
