### ISSUE TITLE
publi and private service

### ISSUE THREAD

**Issue by klag** [jolie/docs#77]
Specify the difference between a public service and a private service here

https://docs.jolie-lang.org/v1.10.x/language-tools-and-standard-library/basics/services.html

**Comment by fmontesi** [comment]
@kicito `private` is just to make it non-importable from other modules, right? Could you add a note?

**Comment by kicito** [comment]
Sure, let me handle it :)

**Comment by fmontesi** [comment]
Can this be closed perhaps?
